config/routes.rb
Rails.application.routes.draw do

  resources :lenders
  resources :borrowers

end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
	has_many :histories
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :lender
  belongs_to :borrower
end

app/models/lender.rb
class Lender < ActiveRecord::Base
	has_many :histories 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  
	before_action :set_borrower, only: [:show, :edit, :update, :destroy]

  def index
  	@borrowers = Borrower.all
  end

  def new
  	@borrower = Borrower.new
  end

  def create
  	# this is the equivalent of a var dump for my form data
  	# render :text => params.inspect
  	@borrower = Borrower.new(borrower_params)
  	#attempt to save borrower to database
  	if @borrower.save
  		flash[:success] = "succesfully created a new borrower. Get ready lenders to provide money"
  		redirect_to borrowers_path
  	else
  		#death
  		@errors = @borrower. errors.full_messages
  		render :new
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @borrower.update(borrower_params)
  		flash[:message] = "Succesfully updated this borrower"
  		redirec_to borrower_path(@borrower)
  	else
  		render :edit
  	end
  end

  private
  def borrower_params
  	params.require(:borrower).permit(:first_name, :last_name, :email, :password, :money, :purpose )
  end
  
  def set_borrower
  	#this runs automtically every time we want it, before the action
  	@borrower = Borrower.find(params[:id])	
  end

end

app/controllers/lenders_controller.rb
class LendersController < ApplicationController

	before_action :set_lender, only: [:show, :edit, :update, :destroy]


  def index
  	@lenders = Lender.all
  end

  def new
  	@lender = Lender.new
  end

  def create
  	# this is the equivalent of a var dumpo for my form data
    # render :text => params.inspect
    @lender = Lender.new(lender_params)
    # attempt to save lender to database
    if @lender.save
      flash[:success] = 'succefully created a new lender. Money will rain down from heaven'
      redirect_to lenders_path
    else
      #death
      @errors = @lender.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

   def update
    if @lender.update(lender_params)
      flash[:message] = "Succesfully updated this lender"
      redirect_to lender_path(@lender)    
    else
      render :edit
    end

  end

  def destroy
  	render :text => params.inspect
  	@lender.destroy(lender_params)
  	flash[:message] = "Forever deleted that lender"
  	# redirect to new_lender_path
  end

  private 
  def lender_params
   params.require(:lender).permit(:first_name, :last_name, :email, :password, :money )
  end

  def set_lender
      #this runs every time we need it to automatically before the action
      @lender= Lender.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/lenders_helper.rb
module LendersHelper
end

app/views/borrowers/create.html.erb
<h1>Borrowers#create</h1>
<p>Find me in app/views/borrowers/create.html.erb</p>

app/views/borrowers/index.html.erb
<h1>Borrowers#index</h1>
<p>Find me in app/views/borrowers/index.html.erb</p>

<h2>List of borrowers</h2>

<% @borrowers.each do |borrower| %>
	<h3>Name: <%= borrower.first_name%> <%= borrower.last_name%></h3>
	<%= link_to 'show', borrower_path(borrower) %>
	<br>
	<%= link_to 'edit', edit_borrower_path(borrower) %>
	<form action='/borrowers/<%= borrower.id %>' method='delete'>
		<a href=""><input type='submit' value='delete'></a>
	</form>
	</h3>

<%end%>
<p>
<%= link_to 'add_new_borrower', new_borrower_path %>

</p>

app/views/borrowers/new.html.erb
<h1>Borrowers#new</h1>
<p>Find me in app/views/borrowers/new.html.erb</p>

<h1>creating a new borrower</h1>
<p>Let's build a form built with form_for</p>

<%= form_for(@borrower) do |f| %>
	<%= f.label :first_name, "First name" %>
	<%= f.text_field :first_name%>
	<%= f.label :last_name, "Last_name" %>
	<%= f.text_field :last_name%>
	<%= f.label :email, "Email" %>
	<%= f.text_field :email %>
	<%= f.label :password, "Password" %>
	<%= f.text_field :password %>
	<%= f.label :money, "Money" %>
	<%= f.text_field :money %>
	<%= f.label :purpose, "Purpose" %>
	<%= f.text_field :purpose %>
	<br>
	<%= f.submit %>

	<%end%>


<p>Now the same form but the usual way</p>
<form action = 'borrowers/create' method='post'>
	First name: <input  type='text' name="first_name">
	Last name: <input type='text' name="last_name">
	Email: <input type='text' name="email">
	Password: <input type='text' name"password">
	Money: <input type='text' name="money">
	Purpose: <input type='text' name='purpose'>
	<br>
	<input type='submit' value='create new'>
</form>

app/views/borrowers/show.html.erb
<h1>Borrowers#show</h1>
<p>Find me in app/views/borrowers/show.html.erb</p>

<h1>Here's the info about: <%= @borrower.first_name %> <%= @borrower.last_name %></h1>
<h2><%= @borrower.email %></h2>
<h2><%= @borrower.password %></h2>
<h2><%= @borrower.money %></h2>
<h2><%= @borrower.purpose%></h2>
<%if flash[:message] %>
	<p><%= flash[:message]%></p>
<%end%>


<p><%= @borrower.first_name%> wants money</p>
<%= link_to "edit this borrower", edit_borrower_path(@borrower)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlackBeltV1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lenders/_form.html.erb
<% if @lender.errors%>
	<% @lender.errors.full_messages.each do |err| %>
		<p class='errors'><%= err %></p>
	<%end%>
<%end%>


<%= form_for(@lender) do |f| %>
	<%= f.label :first_name, "First Name" %>
	<%= f.text_field :first_name %>
	<%= f.label :first_name, "Last Name" %>
	<%= f.text_field :first_name %>
	<%= f.label :email, "email" %>
	<%= f.text_field :email %>
	<%= f.label :password, "password" %>
	<%= f.text_field :password %>
	<%= f.label :money, "money" %>
	<%= f.text_field :money %>
	<br>
	<%= f.submit %>
<% end %>

app/views/lenders/create.html.erb
<h1>Lenders#create</h1>
<p>Find me in app/views/lenders/create.html.erb</p>

app/views/lenders/edit.html.erb
<h1>Lenders#edit</h1>
<h2>Isn't rails nifty</h2>
<%= render 'form'%>

app/views/lenders/index.html.erb
<h1>Lenders#index</h1>
<p>Find me in app/views/lenders/index.html.erb</p>

<h2>List of lenders</h2>

<% @lenders.each do |lender|%>
	<h3>Name: <%=lender.first_name %> <%=lender.last_name %><br> 
		<%= link_to 'show', lender_path(lender)%> <br>
		<%= link_to 'edit', edit_lender_path(lender)%> 
		<form action='/lenders/<%= lender.id %>' method='delete'><a href=""><input type='submit' value='delete'></a></form>
	</h3>
		
<%end%>

<p>
<%= link_to 'add_new_lender', new_lender_path %>

</p>	

app/views/lenders/new.html.erb
<h1>Lenders#new</h1>
<p>Find me in app/views/lenders/new.html.erb</p>

<h1>Creating a new lender</h1>
<p>Let's build a form built with form_for</p>

 <%= form_for(@lender) do |f| %>
	<%= f.label :first_name, "First Name" %>
	<%= f.text_field :first_name %>
	<%= f.label :first_name, "Last Name" %>
	<%= f.text_field :first_name %>
	<%= f.label :email, "email" %>
	<%= f.text_field :email %>
	<%= f.label :password, "password" %>
	<%= f.text_field :password %>
	<%= f.label :money, "money" %>
	<%= f.text_field :money %>
	<br>
	<%= f.submit %>

	<%end%>


<h2>This is the form built using the form_for helper</h2>
<!-- it will render the partial view in _form.html.erb -->

app/views/lenders/show.html.erb
<h1>Lenders#show</h1>
<p>Find me in app/views/lenders/show.html.erb</p>

<h1>Here's the info about: <%= @lender.first_name %> <%= @lender.last_name %></h1>
<h2><%= @lender.email %></h2>
<h2><%= @lender.password %></h2>
<h2><%= @lender.money %></h2>
<%if flash[:message] %>
	<p><%= flash[:message]%></p>
<%end%>


<p><%= @lender.first_name%> can lend you lots of money</p>
<%= link_to "edit this lender", edit_lender_path(@lender)%>